export const SliderData = [
  'https://ludumobucket.s3.eu-central-1.amazonaws.com/Sundry+pics/Knysna1.jpg',
  'https://ludumobucket.s3.eu-central-1.amazonaws.com/Sundry+pics/a.jpg',
  'https://ludumobucket.s3.eu-central-1.amazonaws.com/Sundry+pics/b.jpg',
  'https://ludumobucket.s3.eu-central-1.amazonaws.com/Sundry+pics/c.jpg',
  'https://ludumobucket.s3.eu-central-1.amazonaws.com/Sundry+pics/d.jpg',
  'https://ludumobucket.s3.eu-central-1.amazonaws.com/Sundry+pics/e.jpg',
  'https://ludumobucket.s3.eu-central-1.amazonaws.com/Sundry+pics/f.jpg',
  'https://ludumobucket.s3.eu-central-1.amazonaws.com/Sundry+pics/g.jpg',
  'https://ludumobucket.s3.eu-central-1.amazonaws.com/Sundry+pics/1.jpg',
  'https://ludumobucket.s3.eu-central-1.amazonaws.com/Sundry+pics/2.jpg',
  'https://ludumobucket.s3.eu-central-1.amazonaws.com/Sundry+pics/3.jpg',
  'https://ludumobucket.s3.eu-central-1.amazonaws.com/Sundry+pics/4.jpg',
  'https://ludumobucket.s3.eu-central-1.amazonaws.com/Sundry+pics/5.jpg',
  'https://ludumobucket.s3.eu-central-1.amazonaws.com/Sundry+pics/6.jpg',
  'https://ludumobucket.s3.eu-central-1.amazonaws.com/Sundry+pics/7.jpg',
];
