import Head from 'next/head';
import Link from 'next/link';
import Hero from '../components/Hero';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';
import About from './about';
import Services from './services';
import Contact from '../components/Contact';
import Footer from '../components/Footer';

 const Home = () => {
  return (
    <div>
      <Head>
        <title>Nkosiza Homes</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero 
        bgImage="https://ludumobucket.s3.eu-central-1.amazonaws.com/Trail+Huts/1.jpg" 
        heading='Nkosiza Homes' 
        button='Explore' 
        showButton={true} 
        link='/about' 
        />
     
      <About />
      <Services />
      <Slider slides={SliderData} />
      <Contact />
      <Footer />
    </div>
  );
}

export default Home;