import Head from 'next/head';
import React from 'react';
import Hero from '../components/Hero';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';
import About from './about';
import Services from './services';
import Contact from '../components/Contact';
import Footer from '../components/Footer';
import HomeText from '../components/HomeText';

 const Home = () => {
  return (
    <div>
      <Head>
        <title>Nkosiza Homes</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero 
        bgImage="https://ludumobucket.s3.eu-central-1.amazonaws.com/Trail+Huts/6.jpg" 
        heading='NKOSIZA HOMES' 
        
        />
      <HomeText />
      <About />
      <Services />
      <Slider slides={SliderData} />
      <Contact />
      <Footer />
    </div>
  );
}

export default Home;